# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-09 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('accountid', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name=b'Account Number')),
                ('customer_name', models.CharField(max_length=64, verbose_name=b'Customer Name')),
                ('attention_to', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'Attention To')),
                ('webpage', models.URLField(blank=True, null=True)),
                ('address_1', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'Address Line 1')),
                ('address_2', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'Address Line 2')),
                ('city', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'city')),
                ('province', models.CharField(blank=True, default=b'Ontario', max_length=64, null=True, verbose_name=b'Province or State')),
                ('country', models.CharField(blank=True, default=b'Canada', max_length=40, null=True, verbose_name=b'Country')),
                ('postal_code', models.CharField(blank=True, max_length=15, null=True, verbose_name=b'Postal Code or ZIP')),
                ('gst_tax_exempt', models.BooleanField(default=False, verbose_name=b'GST Tax Exempt?')),
                ('hst_tax_exempt', models.BooleanField(default=False, verbose_name=b'HST Tax Exempt?')),
                ('pst_tax_exempt', models.BooleanField(default=False, verbose_name=b'PST Tax Exempt?')),
                ('gst_number', models.CharField(blank=True, max_length=17, null=True, verbose_name=b'GST number')),
                ('hst_number', models.CharField(blank=True, max_length=17, null=True, verbose_name=b'HST number')),
                ('pst_number', models.CharField(blank=True, max_length=11, null=True, verbose_name=b'PST number')),
                ('foreign_account', models.CharField(blank=True, max_length=30, null=True, verbose_name=b'Our Account # With Them')),
                ('ship_collect', models.BooleanField(default=False, verbose_name=b'Ship Collect?')),
                ('fob', models.CharField(blank=True, default=b'Oshawa, Ontario, Canada', max_length=50, null=True, verbose_name=b'FOB')),
                ('ap_contact', models.TextField(blank=True, help_text=b'Enter Accounts Payable contact name, number and e-mail.', null=True, verbose_name=b'AP contact info')),
                ('comments', models.TextField(blank=True, null=True, verbose_name=b'Comments')),
                ('record_created', models.DateField(auto_now_add=True, null=True)),
                ('last_activity', models.DateField(blank=True, null=True)),
                ('contact_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Config.Config_Contact_Type')),
                ('currency_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Config.Currency_Type')),
                ('delivery_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Config.Config_Delivery_Type')),
                ('terms', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Config.Config_Payment_Terms')),
            ],
            options={
                'ordering': ['customer_name'],
                'db_table': 'contacts',
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Contacts_Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_data', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'Distribution Data')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution', to='Contacts.Contacts')),
                ('distribution_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Config.Distribution_Type', verbose_name=b'Distribution Type')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts_Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'Email Address')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_address', to='Contacts.Contacts')),
                ('email_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Config.Config_Email_Type', verbose_name=b'Type')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts_Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'Phone Number')),
                ('phone_ext', models.CharField(blank=True, max_length=10, null=True, verbose_name=b'Extention')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_number', to='Contacts.Contacts')),
                ('phone_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Config.Phone_Type', verbose_name=b'Type')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('accountid', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name=b'Id')),
                ('login', models.CharField(blank=True, max_length=32, null=True, verbose_name=b'Login Id or MAC Address')),
                ('login_password', models.CharField(blank=True, max_length=32, null=True, verbose_name=b'Login Password')),
                ('vpn_ip', models.CharField(blank=True, max_length=15, null=True, verbose_name=b'VPN Login IP')),
                ('remote_ip', models.CharField(blank=True, max_length=15, null=True, verbose_name=b'Remote IP')),
                ('inside_ip', models.CharField(blank=True, max_length=15, null=True, verbose_name=b'Inside IP')),
                ('locationid', models.TextField(blank=True, default=None, max_length=100, null=True, verbose_name=b'Default Location')),
                ('comments', models.TextField(blank=True, null=True, verbose_name=b'Comments')),
                ('record_created', models.DateTimeField(auto_now_add=True, verbose_name=b'Date Created')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name=b'Date Last Login')),
                ('last_logout', models.DateTimeField(blank=True, null=True, verbose_name=b'Date Last Logout')),
                ('login_status', models.CharField(blank=True, choices=[(b'NEW', b'New Account (Guest Status)'), (b'UP', b'Account Logged In'), (b'DOWN', b'Account Logged Out'), (b'RAD', b'Radius Programming')], default=b'None', max_length=4, null=True, verbose_name=b'Login Status')),
                ('down_alarm_type', models.CharField(blank=True, choices=[(b'NONE', b'None'), (b'EMAIL', b'Email Notification'), (b'CALL', b'Call Notification'), (b'BOTH', b'Email & Call Notification')], default=b'NONE', max_length=4, null=True, verbose_name=b'Alarm Type')),
                ('up_alarm_type', models.CharField(blank=True, choices=[(b'NONE', b'None'), (b'EMAIL', b'Email Notification'), (b'CALL', b'Call Notification'), (b'BOTH', b'Email & Call Notification')], default=b'NONE', max_length=4, null=True, verbose_name=b'Alarm Type')),
                ('last_notification_down', models.DateTimeField(blank=True, null=True, verbose_name=b'Last Notification Sent (Down)')),
                ('last_notification_up', models.DateTimeField(blank=True, null=True, verbose_name=b'Last Notification Sent (Up)')),
                ('email_address_1', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'Email Address One')),
                ('email_address_2', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'Email Address Two')),
                ('email_address_3', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'Email Address Three')),
                ('phone_number_1', models.CharField(blank=True, max_length=32, null=True, verbose_name=b'Phone Number One')),
                ('phone_number_2', models.CharField(blank=True, max_length=32, null=True, verbose_name=b'Phone Number Two')),
                ('phone_number_3', models.CharField(blank=True, max_length=32, null=True, verbose_name=b'Phone Number Three')),
                ('siteid', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_siteid', to='Contacts.Contacts')),
                ('soldto', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_soldto', to='Contacts.Contacts')),
            ],
            options={
                'ordering': ['login'],
                'db_table': 'login',
                'verbose_name': 'Device Login',
                'verbose_name_plural': 'Device Login',
            },
        ),
    ]
