# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-09 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config_Contact_Type',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name=b'Id')),
                ('type', models.CharField(max_length=40, verbose_name=b'Type')),
                ('comments', models.CharField(blank=True, max_length=40, null=True, verbose_name=b'Comments')),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'config_contact_type',
                'verbose_name': 'Contact Mail List Type',
                'verbose_name_plural': 'Contact Mail List Type',
            },
        ),
        migrations.CreateModel(
            name='Config_Data',
            fields=[
                ('variable', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name=b'Variable')),
                ('value', models.CharField(max_length=64, null=True, verbose_name=b'Value')),
                ('comments', models.CharField(max_length=32, null=True, verbose_name=b'Comments')),
            ],
            options={
                'ordering': ['variable', 'value'],
                'db_table': 'system_config_data',
                'verbose_name': 'System Config Data',
                'verbose_name_plural': 'System Config Data',
            },
        ),
        migrations.CreateModel(
            name='Config_Delivery_Type',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name=b'Id')),
                ('type', models.CharField(max_length=40, verbose_name=b'Delivery Type')),
                ('comments', models.CharField(blank=True, max_length=40, null=True, verbose_name=b'Comments')),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'config_delivery_type',
                'verbose_name': 'Delivery Type',
                'verbose_name_plural': 'Delivery Type',
            },
        ),
        migrations.CreateModel(
            name='Config_Email_Type',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name=b'Id')),
                ('type', models.CharField(max_length=40, verbose_name=b'Email Type')),
                ('comments', models.CharField(blank=True, max_length=40, null=True, verbose_name=b'Comments')),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'config_email_type',
                'verbose_name': 'Email Type',
                'verbose_name_plural': 'Email Type',
            },
        ),
        migrations.CreateModel(
            name='Config_Hardware_Type',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name=b'Id')),
                ('type', models.CharField(max_length=40, verbose_name=b'Hardware Model')),
                ('comments', models.CharField(blank=True, max_length=40, null=True, verbose_name=b'Comments')),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'config_hardware_type',
                'verbose_name': 'Hardware Type',
                'verbose_name_plural': 'Hardware Type',
            },
        ),
        migrations.CreateModel(
            name='Config_Payment_Terms',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name=b'Id')),
                ('type', models.CharField(max_length=40, verbose_name=b'Term(s)')),
                ('comments', models.CharField(blank=True, max_length=40, null=True, verbose_name=b'Comments')),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'config_payment_terms',
                'verbose_name': 'Terms',
                'verbose_name_plural': 'Terms',
            },
        ),
        migrations.CreateModel(
            name='Currency_Type',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name=b'Id')),
                ('type', models.CharField(max_length=40, verbose_name=b'Currency Type')),
                ('comments', models.CharField(blank=True, max_length=40, null=True, verbose_name=b'Comments')),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'config_currency_type',
                'verbose_name': 'Currency Type',
                'verbose_name_plural': 'Currency Type',
            },
        ),
        migrations.CreateModel(
            name='Distribution_Type',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name=b'Id')),
                ('type', models.CharField(max_length=40, verbose_name=b'Distribution Type')),
                ('comments', models.CharField(blank=True, max_length=40, null=True, verbose_name=b'Comments')),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'config_distribution_type',
                'verbose_name': 'Distribution Type',
                'verbose_name_plural': 'Distribution Type',
            },
        ),
        migrations.CreateModel(
            name='Phone_Type',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name=b'Id')),
                ('type', models.CharField(max_length=40, verbose_name=b'Phone Type')),
                ('comments', models.CharField(blank=True, max_length=40, null=True, verbose_name=b'Comments')),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'config_phone_type',
                'verbose_name': 'Phone Type',
                'verbose_name_plural': 'Phone Type',
            },
        ),
    ]
