# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-09 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DNS_Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zone', models.CharField(max_length=64, null=True, verbose_name=b'Zone')),
                ('ttl', models.IntegerField(default=3600, verbose_name=b'TTL')),
                ('type', models.CharField(max_length=10, null=True, verbose_name=b'Record Type A,PTR,CNAME')),
                ('host', models.CharField(max_length=64, null=True, verbose_name=b'Host A=Name,PTR=IP')),
                ('data', models.CharField(max_length=255, null=True, verbose_name=b'Data A=IP, PTR=Name')),
                ('mx_priority', models.IntegerField(blank=True, null=True)),
                ('primary_ns', models.CharField(blank=True, default=b'', max_length=64, null=True)),
                ('resp_person', models.CharField(blank=True, default=b'', max_length=20, null=True)),
                ('serial', models.IntegerField(blank=True, null=True)),
                ('refresh', models.IntegerField(blank=True, null=True)),
                ('retry', models.IntegerField(blank=True, null=True)),
                ('expire', models.IntegerField(blank=True, null=True)),
                ('minimum', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, verbose_name=b'Account Enabled?')),
                ('accountid', models.CharField(max_length=10, null=True, verbose_name=b'Account Number')),
            ],
            options={
                'ordering': ['zone', 'type'],
                'db_table': 'dns_data',
                'verbose_name': 'DNS Data',
                'verbose_name_plural': 'DNS/zone List',
            },
        ),
        migrations.CreateModel(
            name='zonesorted',
            fields=[
            ],
            options={
                'ordering': ['data', 'zone'],
                'proxy': True,
            },
            bases=('Dns.dns_data',),
        ),
    ]
